
# Deployment job on Jenkins

- '{name}-free-git':

    name: user-conf
    defaults: std-freestyle-job

    title: 'User Conf - Run'
    htmlDescription: "Init (first time), stat and update. "
    build-summary-image: 'ws/logo.png'
    disabled: true
    concurrent: false

    project-src: '*.rst,*.styl,*.yaml,*.js'
    email-individuals: false
    email-to:
    fail-on-error: true
    unstable-on-warning: true
    publish-on-error: True

    git-url: http://github.com/dotmpe/user-conf.git

    browser: githubweb

    jenkins-home: '/var/lib/jenkins'
    workspace: '/var/lib/jenkins/.conf'

    branch: test
    git-recursive-init: False
    credentials-id: ''

    parameters:
      - string:
          name: SUBCMD
          description: " Available commands are install, stat, update and test. "
          default: update
      - bool:
          name: REINIT
          description: "Set to clean the workspace folder. WARNING: throws away any consolidated, uncommitted files! "

    metadata: []
    properties: []

    builders:
      - shell: |
          test -n "$SUBCMD" || SUBCMD=stat
          test -x "./script/user-conf/$SUBCMD.sh" || exit 12
          test -x "$(which git)" && git status
          case "$REINIT" in 1|true) git clean -dfx ./ ;; esac
          ./script/user-conf/init.sh
          ./script/user-conf/$SUBCMD.sh || {{
            ./script/user-conf/update.sh
          }}
          test -x "$(which git)" && git status
          echo "Jenkins User-Config update finished"

    publishers: []



