
# CI job on Jenkins

- '{name}-gh-travis':

    name: user-conf
    disabled: true
    title: 'User Conf CI Tests [Travis]' 
    build-summary-image: 'ws/logo.png'
    htmlDescription: |
      Build CI test for user-conf. 

    version: 0.0.1-dev # user-conf
    jtb-files: .jtb.yml
    vendor-repo: github
    vendor-path: dotmpe/user-conf
    branch: test
    project-src: '*.rst,*.styl,*.yaml,*.js'
    email-individuals: false
    email-to:

    publishers:
      - tap:
          results: build/test-results.tap

    triggers:
      - pollscm:
          cron: '*/15 * * * *'

