
install: ./install-dependencies.sh

before_script:
- export PATH=$PATH:$PREFIX/bin
- test -d build || mkdir build

branches:
  only:
  - master

script:
- ./script/test.sh > ./build/test-result.tap

after_script:

env:
- ENV=

