
install: ./install-dependencies.sh project test

#before_script: []
#- export PATH=$PATH:$PREFIX/bin

branches:
  only:
  - test
  - dev

script:
- test ! -e ~/.conf/bash/env || . ~/.conf/bash/env
- mkdir -vp build
- ./script/user-conf/test.sh | tee ./build/test-results.tap
- bats --version

#after_script: []
env:
  - Build_Deps_Default_Paths=1 TRAVIS_SKIP=1

