
install: ./install-dependencies.sh project test

#before_script: []
#- export PATH=$PATH:$PREFIX/bin

branches:
  only:
  - test
  - dev

script:
- test !- ~/.conf/bash/env || . ~/.conf/bash/env
- ./tools/ci/test.sh
- bats --version

#after_script: []
env:
  - Build_Deps_Default_Paths=1

