
install: ./install-dependencies.sh

before_script:
- mkdir -vp $HOME/project
- export PATH=$PATH:$PREFIX/bin
- test -d build || mkdir build

branches:
  only:
  - master

script:
- ./script/test.sh | tee ./build/test-result.tap

after_script:

env:
- ENV= PREFIX=$HOME/ SRC_PREFIX=$HOME/project

