
install: ./install-dependencies.sh

#before_script: []
#- export PATH=$PATH:$PREFIX/bin

branches:
  only:
  - test
  - dev

script:
- ./tools/ci/test.sh
- bats --version

#after_script: []
env:
  - Build_Deps_Default_Paths=1

