
install: ./install-dependencies.sh project test

branches:
  only:
    - test
    - dev

script:
  - set -e
  - test ! -e ~/.conf/bash/env || . ~/.conf/bash/env
  - ./tools/ci/test.sh

env:
  - Build_Deps_Default_Paths=1 TRAVIS_SKIP=1 JENKINS_SKIP=1 JTB_VERSION=

