
install: ./install-dependencies.sh project test

branches:
  only:
    - test
    - dev

script:
  - case "$REINIT" in 1|true) git clean -dfx install/ ;; esac
  - set -e
  - . ./bash/env.sh
  - ./tools/ci/test.sh

env:
  - Build_Deps_Default_Paths=1 TRAVIS_SKIP=1 JENKINS_SKIP=1 JTB_VERSION=

