# git-versioning main: user-conf

- type: application/vnd.org.wtwta.project
  main: user-conf
  id: user-conf
  version: 0.0.1-dev # user-conf
  vendor: dotmpe
  distribution: public
  license: GPL

  repositories:
    github: git@github.com:dotmpe/user-conf.git
    dotmpe.origin: git-repos/user-conf.git

  pd-meta:
    init: "./install-dependencies.sh project dev"
    check: ""
    test: "./tools/ci/test.sh"
    build: ""
    tasks:
      document: todo.txt

  scripts:
    ci: # Builds the CI tests
      - eval $( hostname -s | tr 'a-z' 'A-Z' )_SKIP=1
      - ./tools/ci/test.sh

    init:
      - htd package update && htd package remotes-reset
      - vc regenerate

    test:
      - ./run-dev.sh ./bin/uc info
      - ./run-dev.sh dash -lic './bin/uc info'
      - ./run-dev.sh bash -lic './bin/uc info'
      #- ./run-dev.sh dash -lic './bin/uc init'
      #- htd run ci

    update:
      - htd run ci-job-update
      - htd run job-update

    tasks:
      - htd tasks --Check-All-Tags --Check-All-Files

#
